/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

const FONT = '"Inter Variable", Inter, ui-sans-serif, system-ui, sans-serif';

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],

  // Dark mode is set by the host page (data-theme on <html>), falling back to the system setting.
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    boxShadow: {
      top4px: "inset 0 4px 0 0 rgba(0, 0, 0, 0.15)",
      top2px: "inset 0 2px 0 0 rgba(0, 0, 0, 0.15)",
      "2xl": "0 5px 20px 0px rgba(0, 0, 0, 0.10)",
      dialog: "0 10px 40px 0px rgba(0, 0, 0, 0.40)",
    },
    // Colours are CSS variables (styles.css) so that one set of utilities serves light and dark
    // themes. `white` is both surfaces and text on filled buttons: the two swap together in dark mode.
    colors: {
      primary: "var(--fs-primary)",
      primarylight: "var(--fs-primarylight)",
      secondary: "var(--fs-secondary)",
      tertiary: "var(--fs-tertiary)",
      success: "var(--fs-success)",
      successlight: "var(--fs-successlight)",
      warning: "var(--fs-warning)",
      warninglight: "var(--fs-warninglight)",
      delete: "var(--fs-delete)",
      deletelight: "var(--fs-deletelight)",
      error: "var(--fs-delete)",
      errorlight: "var(--fs-deletelight)",
      black: "var(--fs-black)",
      grey1: "var(--fs-grey1)",
      grey2: "var(--fs-grey2)",
      grey3: "var(--fs-grey3)",
      grey4: "var(--fs-grey4)",
      grey5: "var(--fs-grey5)",
      grey6: "var(--fs-grey6)",
      white: "var(--fs-white)",
      transparent: "transparent",
      current: "currentColor",
    },
    extend: {
      opacity: {
        shadow: ".15",
      },
      spacing: {
        "1px": "1px",
        "2px": "2px",
        "3px": "3px",
        "5px": "5px",
        "6px": "6px",
        "7px": "7px",
        "9px": "9px",
        "10px": "10px",
        "11px": "11px",
        "13px": "13px",
        "14px": "14px",
        "15px": "15px",
        "17px": "17px",
        "18px": "18px",
        "19px": "19px",
        "30px": "30px",
        "48px": "48px",
        "44px": "44px",
        "84px": "84px",
        "200px": "200px",
        "224px": "224px",
        30: "120px",
        34: "136px",
        35: "140px",
      },
      width: {
        sidebar: "320px",
        logo: "240px",
        "logo-sm": "48px",
        sheet: "760px",
        form: "400px",
        card: "376px",
        "image-preview": "120px",
        "image-preview-sm": "200px",
        "image-preview-circle": "120px",
        "image-preview-circle-sm": "150px",
        "button-sm": "14px",
        popup: "480px",
        "popup-sm": "520px",
        "popup-md": "730px",
        "popup-lg": "1228px",
      },
      height: {
        footer: "88px",
        logo: "110px",
        table: 384,
        "logo-sm": "48px",
        "image-card": "200px",
        "image-preview": "90px",
        "image-preview-sm": "150px",
        "image-preview-circle": "120px",
        "image-preview-circle-sm": "150px",
        "button-sm": "14px",
      },
      fontFamily: {
        // Inter, as on the study site
        title0: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title1: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title2: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title3: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title4: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title5: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        bodylarge: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        introdesktop: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title6: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        title7: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        caption: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        link: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        subhead: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        button: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        intro: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        bodybold: ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'table-header': ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'table-row': ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'card-key': ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'card-value': ['"Inter Variable"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      // In rem, so text follows the reader's own size setting.
      fontSize: {
        title0: ['2.5rem', '1.15'],
        title1: ['2rem', '1.2'],
        title2: ['1.75rem', '1.2'],
        title3: ['1.5rem', '1.25'],
        title4: ['1.375rem', '1.3'],
        title5: ['1.25rem', '1.3'],
        title6: ['1.125rem', '1.35'],
        title7: ['1rem', '1.4'],
        caption: ['0.875rem', '1.3'],
        captionsmall: ['0.8125rem', '1.25'],
        subhead: ['1.125rem', '1.3'],
        label: ['1rem', '1.25'],
        labelsmall: ['0.875rem', '1.25'],
        button: ['1rem', '1.25'],
        buttonsmall: ['0.9375rem', '1.25'],
        intro: ['1.125rem', '1.6'],
        introdesktop: ['1.25rem', '1.6'],
        bodylarge: ['1.125rem', '1.6'],
        bodymedium: ['1rem', '1.6'],
        bodysmall: ['0.9375rem', '1.55'],
        bodylinklarge: ['1.125rem', '1.6'],
        bodylinkmedium: ['1rem', '1.6'],
        link: ['1rem', '1.5'],
        table: ['0.875rem', '1.35'],
        card: ['0.875rem', '1.35']
      },
      minWidth: {
        '1/2': '50%',
        '3/4': '75%',
      },
      maxWidth: {
        card: "376px",
        form: "400px",
        sheet: "760px",
        popup: "480px",
        "popup-sm": "520px",
        "popup-md": "730px",
        "popup-lg": "1228px",
        "3/4": "75%",
        "9/10": "90%",
      },
      maxHeight: {
        dropdown: "317px",
        header1: "376px",
        form: "400px",
        mailto: "128px",
      },
    },
  },
  variants: {
    extend: {
      borderColor: ["active", "hover", "disabled"],
      borderWidth: ["active", "hover", "disabled"],
      ringColor: ["hover"],
      ringWidth: ["hover"],
      ringOpacity: ["hover"],
      ringOffsetColor: ["hover"],
      ringOffsetWidth: ["hover"],
      opacity: ["active", "disabled"],
      padding: ["active"],
      boxShadow: ["active"],
    },
  },
  plugins: [
    plugin(function ({ addUtilities, addComponents }) {
      addUtilities({
        ".h-viewport": {
          height: "calc(var(--vh, 1vh) * 100)",
        },
        ".scrollbar-hide": {
          /* Firefox */
          "scrollbar-width": "thin",

          /* Safari and Chrome */
          "&::-webkit-scrollbar": {
            display: "none",
          },
        },
      });

      /* Font classes: Inter, as on the study site; bold titles, regular (not light) body text */
      addComponents({
        ".font-title0": { "font-family": FONT, "font-weight": "700" },
        ".font-title1": { "font-family": FONT, "font-weight": "700" },
        ".font-title2": { "font-family": FONT, "font-weight": "700" },
        ".font-title3": { "font-family": FONT, "font-weight": "700" },
        ".font-title4": { "font-family": FONT, "font-weight": "700" },
        ".font-title5": { "font-family": FONT, "font-weight": "700" },
        ".font-bodylarge": { "font-family": FONT, "font-weight": "400" },
        ".font-introdesktop": { "font-family": FONT, "font-weight": "500" },
        ".font-title6": { "font-family": FONT, "font-weight": "700" },
        ".font-title7": { "font-family": FONT, "font-weight": "700" },
        ".font-caption": { "font-family": FONT, "font-weight": "500" },
        ".font-link": { "font-family": FONT, "font-weight": "500" },
        ".font-subhead": { "font-family": FONT, "font-weight": "600" },
        ".font-button": { "font-family": FONT, "font-weight": "700" },
        ".font-intro": { "font-family": FONT, "font-weight": "500" },
        ".font-label": { "font-family": FONT, "font-weight": "700" },
        ".font-body": { "font-family": FONT, "font-weight": "400" },
        ".font-bodybold": { "font-family": FONT, "font-weight": "500" },
        ".font-table-header": { "font-family": FONT, "font-weight": "700" },
        ".font-table-row": { "font-family": FONT, "font-weight": "400" },
        ".font-card-key": { "font-family": FONT, "font-weight": "500" },
        ".font-card-value": { "font-family": FONT, "font-weight": "400" },
      });
    }),
  ],
};
